# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Part of BlueTit Solver, under the MIT License.
# See /LICENSE.md for license information. SPDX-License-Identifier: MIT
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

name: "Setup vcpkg"
description: "Setup vcpkg and install the manifest dependencies."

runs:
  using: "composite"
  steps:
    - name: Setup vcpkg
      shell: bash
      run: |
        # Install vcpkg.
        VCPKG_ROOT="$HOME/vcpkg"
        if [ ! -d "$VCPKG_ROOT" ]; then
          git clone https://github.com/microsoft/vcpkg.git "$VCPKG_ROOT"
        fi

        # Bootstrap vcpkg.
        eval "$VCPKG_ROOT/bootstrap-vcpkg.sh" -disableMetrics
        echo "VCPKG_ROOT=$VCPKG_ROOT" >> "$GITHUB_ENV"

        # Setup the default binary cache location.
        VCPKG_DEFAULT_BINARY_CACHE="$HOME/.cache/vcpkg/archives"
        mkdir -p "$VCPKG_DEFAULT_BINARY_CACHE" || true
        echo "VCPKG_DEFAULT_BINARY_CACHE=$VCPKG_DEFAULT_BINARY_CACHE" >> "$GITHUB_ENV"
        echo "VCPKG_BINARY_SOURCES=clear;default,readwrite" >> "$GITHUB_ENV"

    - name: Identify compiler hash
      shell: bash
      run: |
        CC=${CC:-cc}
        CC_HASH=$($CC --version | head -n 1 | sha1sum | cut -d' ' -f1)
        CXX=${CXX:-c++}
        CXX_HASH=$($CXX --version | head -n 1 | sha1sum | cut -d' ' -f1)
        echo "COMPILER_HASH=${CC_HASH}-${CXX_HASH}" >> "$GITHUB_ENV"

    - name: Restore vcpkg binary cache
      id: vcpkg-cache-restore
      uses: actions/cache@v4
      with:
        key: vcpkg-bin-${{ runner.os }}-${{ env.COMPILER_HASH }}-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          vcpkg-bin-${{ runner.os }}-${{ env.COMPILER_HASH }}-
        path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}

    - name: Install vcpkg packages
      shell: bash
      run: $VCPKG_ROOT/vcpkg install --no-print-usage
