# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Part of the Tit Solver project, under the MIT License.
# See /LICENSE.md for license information. SPDX-License-Identifier: MIT
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

version: 2.1

executors:
  linux-arm64:
    resource_class: arm.medium
    docker:
      - image: jhuighuy/tit-solver-base:latest

jobs:
  build:
    parameters:
      os:
        type: executor
      compiler:
        type: string
      configuration:
        type: string

    executor: << parameters.os >>

    steps:
      - checkout

      # Build and test.
      - run: |
          ./build/build.sh -j 2                                                \
            --compiler << parameters.compiler >>                               \
            --config << parameters.configuration >>                            \
            --force                                                            \
            --test

      # Upload test results.
      - store_test_results:
          path: output/test_output/JUnit.xml

      # Upload test output.
      - store_artifacts:
          path: output/test_output

workflows:
  all_build:
    jobs:
      - build:
          matrix: # Extra indentation is intentional.
            parameters:
              os: [linux-arm64]
              compiler: ["g++-14"]
              configuration: ["Debug"] # Minimize build time, thus only Debug.
