# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Part of BlueTit Solver, under the MIT License.
# See /LICENSE.md for license information. SPDX-License-Identifier: MIT
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

name: "Setup Runner"
description: "Setup the runner with the specified compiler and dependencies."

inputs:
  compiler:
    description: "Compiler (`GCC` or `Clang`)."
    required: true
  gcc-version:
    description: "Version of GCC to use."
  llvm-version:
    description: "Version of LLVM to use."

runs:
  using: "composite"
  steps:
    - name: Setup Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Setup Homebrew packages
      shell: bash
      run: |
        # ----------------------------------------------------------------------
        #
        # Setup environment variables.
        #

        BREW_PREFIX="$(brew --prefix)"
        GCC_VERSION="${{ inputs.gcc_version || '15' }}"
        LLVM_VERSION="${{ inputs.llvm_version || '22' }}"

        # ----------------------------------------------------------------------
        #
        # Install packages.
        #

        PACKAGES=(
          binutils
          cmake
          codespell
          gcc@$GCC_VERSION
          gcovr
          llvm@$LLVM_VERSION
          node
          pnpm
          sphinx-doc
        )

        if [[ "$OSTYPE" == "darwin"* ]]; then
          sudo xcode-select -s /Library/Developer/CommandLineTools
          PACKAGES+=(
            diffutils
            gnu-sed
          )
        fi

        HOMEBREW_NO_AUTO_UPDATE=1 brew install --quiet "${PACKAGES[@]}"

        # ----------------------------------------------------------------------
        #
        # Setup compilers.
        #

        # Add GCC tools to the path and create versioned symlinks.
        GCC_ROOT="$(brew --prefix gcc@$GCC_VERSION)"
        GCC_PATH="$GCC_ROOT/bin"
        for TOOL in gcc g++ gcov; do
           if [[ ! -f "$GCC_PATH/$TOOL-$GCC_VERSION" ]]; then
             ln -s "$GCC_PATH/$TOOL" "$GCC_PATH/$TOOL-$GCC_VERSION"
           fi
        done
        echo "$GCC_PATH" >> "$GITHUB_PATH"

        # Add LLVM tools to the path and create versioned symlinks.
        LLVM_ROOT="$(brew --prefix llvm@$LLVM_VERSION)"
        LLVM_PATH="$LLVM_ROOT/bin"
        for TOOL in clang clang++ clang-format clang-tidy; do
           if [[ ! -f "$LLVM_PATH/$TOOL-$LLVM_VERSION" ]]; then
             ln -s "$LLVM_PATH/$TOOL" "$LLVM_PATH/$TOOL-$LLVM_VERSION"
           fi
        done
        echo "$LLVM_PATH" >> "$GITHUB_PATH"

        # Select the compiler from the arguments.
        case "${{ inputs.compiler }}" in
          GCC)
            CC="gcc-$GCC_VERSION"
            CXX="g++-$GCC_VERSION"

            if [[ "$OSTYPE" == "linux-gnu"* ]]; then
              # System binutils might not be compatible with the latest GCC.
              BINUTILS_PREFIX="$(brew --prefix binutils)"
              echo "$BINUTILS_PREFIX/bin" >> "$GITHUB_PATH"
            fi
            ;;

          Clang)
            CC="clang-$LLVM_VERSION"
            CXX="clang++-$LLVM_VERSION"

            if [[ "$OSTYPE" == "linux-gnu"* ]]; then
              # Use libstdc++ from our GCC installation.
              GCC_INC_PATH="$GCC_ROOT/include/c++/$GCC_VERSION"
              GCC_LIB_PATH="$GCC_ROOT/lib/gcc/$GCC_VERSION"
              ISYSTEM_FLAGS="-isystem $GCC_INC_PATH -isystem $GCC_INC_PATH/x86_64-pc-linux-gnu"
              CFLAGS="$CFLAGS $ISYSTEM_FLAGS"
              CXXFLAGS="$CXXFLAGS $ISYSTEM_FLAGS"
              LDFLAGS="$LDFLAGS -L$GCC_LIB_PATH -Wl,-rpath,$GCC_LIB_PATH"

              # Use Brew libraries.
              BREW_LIB_PATH="$BREW_PREFIX/lib"
              LDFLAGS="$LDFLAGS -L$BREW_LIB_PATH -Wl,-rpath,$BREW_LIB_PATH"
            fi
            ;;

          *)
            echo "::error::Unknown compiler: '${{ inputs.compiler }}'."
            exit 1
            ;;
        esac

        # ----------------------------------------------------------------------
        #
        # Export variables.
        #

        # Toolchain configuration.
        echo "CC=$CC" >> "$GITHUB_ENV"
        echo "CXX=$CXX" >> "$GITHUB_ENV"
        echo "CPPFLAGS=$CPPFLAGS" >> "$GITHUB_ENV"
        echo "CFLAGS=$CFLAGS" >> "$GITHUB_ENV"
        echo "CXXFLAGS=$CXXFLAGS" >> "$GITHUB_ENV"
        echo "LDFLAGS=$LDFLAGS" >> "$GITHUB_ENV"
