# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Part of BlueTit Solver, licensed under Apache 2.0 with Commons Clause.
# Commercial use, including SaaS, requires a separate license, see /LICENSE.md
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

inputs:
  compiler:
    description: "Compiler (`GCC` or `Clang`)."
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Setup runner
      shell: bash
      run: |
        # Select the compiler from the arguments.
        GCC_VERSION=${GCC_VERSION:-15}
        LLVM_VERSION=${LLVM_VERSION:-20}
        case "${{ inputs.compiler }}" in
          GCC)
            export CC="gcc-$GCC_VERSION"
            export CXX="g++-$GCC_VERSION"
            ;;
          Clang)
            export CC="clang-$LLVM_VERSION"
            export CXX="clang++-$LLVM_VERSION"
            ;;
          *)
            echo "Unknown compiler: '$1'. Must be either 'GCC' or 'Clang'."
            exit 1
            ;;
        esac
        echo "CC=$CC" >> "$GITHUB_ENV"
        echo "CXX=$CXX" >> "$GITHUB_ENV"

        # Select packages to install.
        PACKAGES=(
          cmake
          codespell
          "gcc@$GCC_VERSION"
          gcovr
          "llvm@$LLVM_VERSION"
          node
          pnpm
          sphinx-doc
        )
        if [[ "$OSTYPE" == "darwin"* ]]; then
          PACKAGES+=(
            diffutils
            gnu-sed
          )
        fi

        # Install packages.
        #
        # Upon installation, Homebrew will automatically update itself and
        # upgrade all installed packages that depend on those we are installing
        # or upgrading. The below variables prevent Homebrew from doing this.
        export HOMEBREW_NO_AUTO_UPDATE=1
        export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
        export HOMEBREW_NO_INSTALL_CLEANUP=1
        brew update -q
        brew install -q "${PACKAGES[@]}" || true # Continue on failure.

        # Add LLVM tools to the path.
        LLVM_PATH="$(brew --prefix "llvm@$LLVM_VERSION")/bin"
        ln -s "$LLVM_PATH/clang++" "$LLVM_PATH/clang++-$LLVM_VERSION"
        echo "$LLVM_PATH" >> "$GITHUB_PATH"

        # Add Sphinx to the path.
        SPHINX_PATH="$(brew --prefix sphinx-doc)/bin"
        echo "$SPHINX_PATH" >> "$GITHUB_PATH"

        # On Linux GCC must use GNU Binutils provided by Homebrew.
        if [[ "$OSTYPE" == "linux-gnu"* ]]; then
          BINUTILS_PATH="$(brew --prefix binutils)/bin:$PATH"
          echo "$BINUTILS_PATH" >> "$GITHUB_PATH"
          LDFLAGS="-L$(brew --prefix binutils)/lib $LDFLAGS"
          CPPFLAGS="-I$(brew --prefix binutils)/include $CPPFLAGS"
          echo "LDFLAGS=$LDFLAGS" >> "$GITHUB_ENV"
          echo "CPPFLAGS=$CPPFLAGS" >> "$GITHUB_ENV"
        fi
