# pylint: disable=unused-argument
from __future__ import annotations

def hello() -> str: ...
def echo(arg: str) -> str: ...
def echo_kwargs(p: int, q: int, a: int = 1, b: int = 2) -> str: ...

class TestClass:
    def __init__(self, value: int) -> None: ...
    def hello_w(self) -> tuple[str, TestClass]: ...
    @property
    def a(self) -> int: ...
    @a.setter
    def a(self, value: int) -> None: ...
