# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Part of BlueTit Solver, under the MIT License.
# See /LICENSE.md for license information. SPDX-License-Identifier: MIT
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

name: Analyze

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

# Cancel previous runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Analyze

    strategy:
      matrix:
        os: [ubuntu-24.04]
        compiler: [GCC]
        configuration: [Coverage]

    runs-on: ${{ matrix.os }}

    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory
      CODECOV_REPORT: cxx_coverage_codecov.xml
      SONAR_REPORT: cxx_coverage_sonar.xml

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all history for proper analysis and coverage reports.
          fetch-depth: 0

      - name: Install Sonar Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v6.0.0

      - name: Setup runner
        uses: ./.github/actions/setup_runner
        with:
          compiler: ${{ matrix.compiler }}

      - name: Setup vcpkg
        uses: ./.github/actions/setup_vcpkg

      - name: Build and test
        run: |
          build-wrapper-linux-x86-64                                           \
            --out-dir "${{ env.BUILD_WRAPPER_OUT_DIR }}"                       \
            ./build/build.sh --config ${{ matrix.configuration }} --test

      - name: Upload test output
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-output-${{ runner.os }}-${{ matrix.compiler }}-${{ matrix.configuration }}
          path: output/test_output

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          slug: Jhuighuy/TitSolver
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ env.CODECOV_REPORT }}
          disable_search: true

      - name: Run Sonar Scanner
        uses: SonarSource/sonarqube-scan-action@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define "sonar.cfamily.experimental.cpp26.enabled=true"
            --define "sonar.cfamily.build-wrapper-output=${{ env.BUILD_WRAPPER_OUT_DIR }}"
            --define "sonar.coverageReportPaths=${{ env.SONAR_REPORT }}"
