# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Part of the Tit Solver project, under the MIT License.
# See /LICENSE.md for license information. SPDX-License-Identifier: MIT
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

name: Docker

on:
  # Run every Sunday at midnight UTC.
  schedule:
    - cron: "0 0 * * 0"
  # Run on main branch if Dockerfile or packages were updated.
  push:
    branches:
      - main
    paths:
      - "docker/**Dockerfile"
      - "vcpkg.json"
  # Run on PR branch if Dockerfile were updated. Updates in packages are
  # cached separately in PR action runs.
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "docker/**Dockerfile"

# Cancel previous runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_docker_images:
    name: Build Docker Images

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          tags: jhuighuy/tit-solver-base:latest
          file: docker/Dockerfile
          platforms: "linux/arm64,linux/amd64"
          push: true
